config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => 'homes#top'
  get "home/about" => "homes#about", as: "about"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]

  resources :chats, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

   validates :message, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(weight, height)
    if profile_image.attached?
      profile_image
    else
      'no_image.jpg'
    end
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books = Book.page(params[:page]).per(20)
  end

  def show
    @book = Book.find(params[:id])
    @books = @user.books.page(params[:page]).per(20)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book), notice: "You have created book successfully!"
    else
      @books = Book.all
      render 'index'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully!"
    else
      render 'edit'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :reject_non_related, only: [:show]

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      if @room.save
        UserRoom.create(user_id: current_user.id, room_id: @room.id)
        UserRoom.create(user_id: @user.id, room_id: @room.id)
        @chats = @room.chats  # ここで @chats をセットする
  　　　　  @chat = Chat.new(room_id: @room.id)
      else
        flash[:alert] = 'Room creation failed!'
        redirect_to user_path(@user)
        return
      end
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    render :validater unless @chat.save
  end


  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def reject_non_related
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
		redirect_to request.referer
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
		redirect_to request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
		@users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
		@users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully!"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control book_title" %>
  </div>
	<div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class:"form-control book_body" %>
  </div>
  <div class="form-group">
  <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>

<% end %>

app/views/books/_index.html.erb
<div class="table">
  <table class="table table-hover">

    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
     </tr>
    </thead>

    <tbody>
      <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to book.user do %>
           <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>

        <td>
          <%= link_to book_path(book.user) do %>
          <%= book.title %>
          <% end %>
        </td>

        <td>
          <%= book.body %>
        </td>
      </tr>
      <% end %>
    </tbody>

  </table>

</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
      	<div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form-group">
        <%= f.submit 'Update Book', class:"btn btn-success" %>
        </div>
       </div>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <%= render 'index', books: @books %>
    </div>
    <div>
    <%= paginate books, theme: 'page' %>
    </div>


  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>

   <div class="col-md-8 offset-md-1 mt-4">
    <h2>Book detail</h2>
     <table class="table table-hover table-inverse">
      <tbody>
       <tr>
        <td>
          <%= link_to @book.user do %>
          <%= image_tag @book.user.get_profile_image(50,50) %><br>
          <%= @book.user.name %>
          <% end %>
        </td>

        <td><%= link_to @book.title, book_path(@book.id) %></td>
        <td><%= @book.body %></td>

        <% if @book.user == current_user %>
          <td><%= link_to "Edit", edit_book_path %></td>
          <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>


       </tr>
      </tbody>
     </table>
    </div>


  </div>
</div>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: right;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<h1 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>"><%= @user.name %> さんとのチャット</h1>

<div class="message" style="width: 400px;">
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
</div>

<div class="errors">
  <%= render "layouts/errors", obj: @chat %>
</div>

<%= form_with model: @chat, data: {remote: true} do |f| %>
  <%= f.text_field :message %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
<% end %>

app/views/chats/validater.js.erb
$('.errors').html("<%= j(render 'layouts/errors', obj: @chat) %>");

app/views/homes/about.html.erb
<div class="container">
 <div class ="row justify-content-center mt-3">
 <h1>Welcome to
 <i class="fa-solid fa-book" style="color: #000000;"></i>
 <span class="fw-bolder">Bookers!</span>
 </h1>
 </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 offset-3 mt-2">
      <h1>welcome to <i class="fa-solid fa-book" style="color: #000000;"></i> Bookers !!</h1>

      <div>
      <p>In <i class="fa-solid fa-book" style="color: #000000;"></i> Bookers,</p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>

      <p>about various books!</p>
      </div>
    </div>

    <div class="col-md-6 offset-3">
      <%= link_to new_user_session_path, class:"text-light text-decoration-none" do %>
      <button type="button" class="btn btn-info btn-sm btn-block mt-3 mb-3">Log in</button>
      <% end %>

      <%= link_to new_user_registration_path, class:"text-light text-decoration-none" do %>
      <button type="button" class="btn btn-success btn-sm btn-block mt-3 mb-3">Sign up</button>
      <% end %>
    </div>
   </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
  <div class="container">
    <p class="text-muted text-center">CopyRight Infratop.inc</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Bookers", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav me-auto mb-2 ml-auto mb-lg-0">
       <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user.id), class:'nav-link text-light' do %>
          <i class="fa-solid fa-house" style="color: #ffffff;"></i> Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class:'nav-link text-light' do %>
          <i class="fa-solid fa-users" style="color: #ffffff;"></i> Users
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to books_path, class:'nav-link text-light' do %>
          <i class="fa-solid fa-book-open" style="color: #ffffff;"></i> Books
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
          <i class="fa-solid fa-right-from-bracket" style="color: #ffffff;"></i> Log out
          <% end %>
        </li>

       <% else %>
        <li class="nav-item">
          <%= link_to root_path, class:'nav-link text-light' do %>
          <i class="fa-solid fa-house" style="color: #ffffff;"></i> Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to about_path, class:'nav-link text-light' do %>
          <i class="fa-solid fa-link" style="color: #ffffff;"></i> About
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
          <i class="fa-solid fa-user-plus" style="color: #ffffff;"></i> Sign up
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class:'nav-link text-light' do %>
          <i class="fa-solid fa-right-to-bracket" style="color: #ffffff;"></i> Log in
          <% end %>
        </li>
       <% end %>
      </ul>

    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2New</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f8a9d9d059.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header', user: @user, book: @book %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/_btn.html.erb
<% if current_user != user%>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/_index.html.erb
<div class="table">
  <table class="table table-hover">

    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
     </tr>
    </thead>

    <tbody>
      <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td class="text-decoration-none"><%= user.name %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/users/_info.html.erb
     <table class="table">
        <tbody>
          <tr><%= image_tag user.get_profile_image(100,100) %></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to user.followings.count, user_followings_path(user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to user.followers.count, user_followers_path(user) %></th>
          </tr>
        </tbody>
      </table>

<div class="row">
  <% if current_user != user %>
     <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
     <i class="fa-solid fa-user-gear" style="color: #76797f;"></i>
     <% end %>
  <% end %>

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <td><%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %></td>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>

<%= form_with model:@user, local:true do |f| %>

 <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
       </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>


    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <%= render 'books/index', books: @books %>
    </div>

  </div>
</div>